# Generated by Django 2.2.16 on 2022-07-06 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('eb5650b6-fd18-11ec-80b9-9439e596a226'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
