# Generated by Django 2.2.16 on 2022-07-02 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('aff467b2-fa3b-11ec-a572-00d86116b68e'), max_length=100, null=True),
        ),
    ]
