# Generated by Django 2.2.16 on 2022-07-06 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220706_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('3312b4d9-fd19-11ec-a47a-9439e596a226'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
