# Generated by Django 2.2.16 on 2022-07-06 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220706_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('fdbcf965-fd1e-11ec-96bd-9439e596a226'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
