# Generated by Django 2.2.16 on 2022-07-02 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220703_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('4b449b91-fa44-11ec-8155-00d86116b68e'), max_length=100, null=True),
        ),
    ]
