# Generated by Django 2.2.16 on 2022-07-03 00:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220702_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('4d99359a-fa6b-11ec-a396-70665589bd78'), max_length=100, null=True),
        ),
    ]
